### PR TITLE
Add SkipOne trait and IgnoredAny and RawValue structs that make use of it

### PR DESCRIPTION
**Pull request by rklaehn**
Not sure about proto, but the SkipOne trait could definitely also be implemented for json. I think proto would work as well...

### CODE REVIEW

**Comment by rklaehn** [comment]
This is pretty simple, and now also has some tests, so I think it is ready to go. Feel free to move things around to where you want them.

**Review by vmx — APPROVED** [review]
There's an unused import. but the rest looks good to me.

**Review by dvc94ch — APPROVED** [review]
We're acruing a lot of custom cbor walkers. Maybe a visitor pattern isn't that bad after all?

**Comment by rklaehn** [comment]
> We're acruing a lot of custom cbor walkers. Maybe a visitor pattern isn't that bad after all?

We can do that later, since it would not change the public API of IgnoredAny or but tbh I don't mind working with bytes. I will take having to check a byte for a value over wading through a maze of traits like in serde...

**Pull request merged**
