### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by dvc94ch**
This is wip. The multihash fork needs to be resolved as fasthash doesn't build on windows.

### CODE REVIEW

**Comment by koivunej** [comment]
Since we have to do similar for other repos, an I am quite new to github workflows, could you link the source you used for these workflows unless you wrote them yourself? I had been looking at https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml as a starting point, but in the ci.yml in this draft at least the actions come from different repository. Do you have any handle on which one of these is more recent/suggested/most official? :)

**Comment by dvc94ch** [comment]
I used `actions-rs` first, but it seems more complicated and I think I had some issues with caching the cargo folder, but I don't remember what it was.

**Comment by vmx** [comment]
As an inspiration: some multiformats repos were moved from Travis to GitHub Actions, e.g. https://github.com/multiformats/rust-multihash/pull/57 and seems to work well: https://github.com/multiformats/rust-multihash/actions/runs/48816477

**Comment by dvc94ch** [comment]
Superceeded by #22

**Pull request closed without merging**
