### PR TITLE
Update `cid` and `multihash` in `core`

### PR DESCRIPTION
**Pull request by tyshko5**

### CODE REVIEW

**Comment by tyshko5** [comment]
@Stebalien @vmx Could you give an approval so it could pass to the checks?

**Review by vmx — CHANGES_REQUESTED** [review]
Please update `cid` and `multihash` for all crates of this project.

**Review by Stebalien — APPROVED** [review]

**Comment by tyshko5** [comment]
@Stebalien @vmx Are you going to release a new version for `libipld` and it's subcrates? That would be very helpful for updating a lot of crates that are depending on it.

**Comment by vmx** [comment]
Yes, I was waiting for this PR (also other folks really want a release). Though I wondered if we can also get the quickcheck one in before doing a release.

**Comment by vmx** [comment]
After a second thought, based on the PR comments on the quickcheck change, it might still need some work and it also is not a breaking change. Hence releasing a new libpld version now.

**Comment by vmx** [comment]
New 0.15 release is out.

**Pull request merged**
