### PR TITLE
dag-cbor: Implement Encode/Decode for NonZero*

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Done in the obvious way.

CI failure is spurious due to #191, once that it merged I'll rebase and it'll go green 🤞

### CODE REVIEW

**Review by vmx — COMMENTED** [review]
Thanks a lot, the change looks good (waiting for the rebase before approving it).

I'd just like to note that this DAG-CBOR implementation is kind of the legacy one. I recommend everyone looking into https://github.com/ipld/serde_ipld_dagcbor instead.

**Comment by aDotInTheVoid** [comment]
> (waiting for the rebase before approving it)

Rebased

>  I recommend everyone looking into https://github.com/ipld/serde_ipld_dagcbor instead.

I wan't to avoid using serde for this. My use case is implementing the [atproto data model](https://atproto.com/specs/data-model#bytes), which requires different handling of bytes depending on if you're encoding to CBOR or JSON.

Eg:

```json
{
  "exampleBytes": {
    "$bytes": "nFERjvLLiw9qm45JrqH9QTzyC2Lu1Xb4ne6+sBrCzI0"
  }
}
```

Should be encoded in CBOR as an object with key `exampleBytes` and a Byte String (Major 2). I don't think there's a way for serde to know what format it's serializing to, so for now it's easier for everything to derive both `Serialize` and `DagCbor`.

If you've got ideas to work around this, I'd love to hear them.

**Review by vmx — APPROVED** [review]

**Comment by vmx** [comment]
Thanks for you contributions. In regards to your question. I don't know what exactly what you're doing, but I tried to come up with something which might help:

```rust
use serde::{ser::SerializeStruct, Deserialize, Deserializer, Serialize, Serializer};

#[derive(Debug, Deserialize, Serialize)]
struct Example {
    #[serde(rename = "exampleBytes")]
    example_bytes: Vec<u8>,
}

#[derive(Debug, Deserialize, Serialize)]
struct ExampleJson {
    #[serde(with = "Wrapper", rename = "exampleBytes")]
    example_bytes: Vec<u8>,
}

impl From<ExampleJson> for Example {
    fn from(other: ExampleJson) -> Self {
        Self {
            example_bytes: other.example_bytes,
        }
    }
}

// Based on https://stackoverflow.com/questions/54657873/is-there-a-way-to-omit-wrapper-root-objects-when-deserializing-objects-with-serd/54658155#54658155
#[derive(Deserialize, Serialize)]
struct Wrapper<T> {
    #[serde(rename = "$bytes")]
    bytes: T,
}

impl<T> Wrapper<T> {
    fn deserialize<'de, D>(deserializer: D) -> Result<T, D::Error>
    where
        T: Deserialize<'de>,
        D: Deserializer<'de>,
    {
        let wrapper = <Self as Deserialize>::deserialize(deserializer)?;
        Ok(wrapper.bytes)
    }

    fn serialize<S>(data: &T, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
        T: Serialize,
    {
        let mut state = serializer.serialize_struct("Wrapper", 1)?;
        state.serialize_field("$bytes", &data)?;
        state.end()
    }
}

fn main() {
    let input_json = r#"{
  "exampleBytes": {
    "$bytes": [1,2,3]
  }
}"#;

    let parsed_input: ExampleJson = serde_json::from_str(input_json).unwrap();
    println!("parsed: {:?}", parsed_input);
    let example: Example = parsed_input.into();
    println!("example: {:?}", example);
    let cbor = serde_ipld_dagcbor::to_vec(&example);
    println!("cbor: {:02X?}", cbor);
}
```

I'm happy to discuss it further if that's not your use case, as I'd really like to get people using `serde_ipld_dagcbor` instead of this DAG-CBOR crate.

**Comment by vmx** [comment]
Or, if that suits you better, feel free to open an issue on the https://github.com/ipld/serde_ipld_dagcbor repo with the problem you are having and we go from there.

**Pull request merged**
