### PR TITLE
fix: remove unnecessary trait bounds

### PR DESCRIPTION
**Pull request by vmx**
I don't know what they are here for, perhaps some development left-over? If they have their use, it would be nice to have tests that enforces them.

### CODE REVIEW

**Comment by dvc94ch** [comment]
Those trait bounds are necessary

**Comment by dvc94ch** [comment]
You can't use a Raw codec if the Multicodec doesn't include a Raw variant

**Comment by vmx** [comment]
> You can't use a Raw codec if the Multicodec doesn't include a Raw variant

Let me try to write a test for that.

**Comment by dvc94ch** [comment]
A block's types are based on the codecs hashes a store supports. The From/Into is used to mark compatibility between a codec and the one the block is parameterized over. To be compatible, the code assigned in the store codec table needs to be the same as the one assigned by the codec.

**Comment by dvc94ch** [comment]
Otherwise there's the issue that the codec will produce an incompatible cid, so we define at compile time that they are compatible, we could check and return an error at runtime instead, but I don't like that solution

**Comment by dvc94ch** [comment]
We should add a debug_assert to check that they result in the same codec code

**Pull request closed without merging**
